import { defineConfig } from '@hey-api/openapi-ts';

// Use local file generated by Gradle build, fall back to live endpoint for dev
const openApiInput = process.env.OPENAPI_LIVE === 'true'
  ? 'http://localhost:8080/q/openapi'
  : './openapi/openapi.yaml';

export default defineConfig({
  input: openApiInput,
  output: {
    path: 'src/api/generated',
    format: 'prettier',
  },
  plugins: [
    '@hey-api/typescript',
    '@hey-api/sdk',
    '@hey-api/client-fetch',
  ],
});
